
[platformio]
include_dir = Inc
src_dir = Src
default_envs = gd32f303cc_usb
 
[common]
#platform_packages = 
#    framework-spl-gd32@https://github.com/CommunityGD32Cores/gd32-pio-spl-package.git
monitor_speed = 115200
build_flags = 
  -I .
  -I grbl
  -I Inc
#  -I FatFs
  -I Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc
  -I Middlewares/ST/STM32_USB_Device_Library/Core/Inc
  -I USB_DEVICE/App
  -I USB_DEVICE/Target
#  -I GD32F30x_usbd_library/class/device/cdc/Include
#  -I GD32F30x_usbd_library/device/Include
  -D RX_BUFFER_SIZE=512
#   Default NVS_size is 2048
#  -D NVS_SIZE=1536
  -D STM32F303xC
#  -D PIO_USBFS_DEVICE_CDC
#lib_deps = GD32F30x_usbd_library
lib_deps =
  grbl
lib_extra_dirs =
  .
#  -D OVERRIDE_MY_MACHINE

[env]
#platform = ststm32
platform = https://github.com/CommunityGD32Cores/platform-gd32.git
framework = spl
# Do not produce .a files for lib deps (which would prevent them from overriding weak symbols)
lib_archive = no
lib_ldf_mode = off

[env:gd32f303cc]
board = genericGD32F303CC
build_flags = ${common.build_flags}
lib_deps = ${common.lib_deps}
lib_extra_dirs = ${common.lib_extra_dirs}
upload_protocol = stlink

[env:gd32f303cc_usb]
board = genericGD32F303CC
build_flags = ${common.build_flags}
  -D USB_SERIAL_CDC=1
lib_deps = ${common.lib_deps}
  Core
  Class
  App
  Target
lib_extra_dirs = ${common.lib_extra_dirs}
  Middlewares/ST/STM32_USB_Device_Library
  USB_DEVICE
upload_protocol = stlink