
[platformio]
include_dir = Inc
src_dir = Src
# default_envs = gd32f303cc_usb

[common]
platform_packages = 
    framework-spl-gd32@https://github.com/CommunityGD32Cores/gd32-pio-spl-package.git
monitor_speed = 115200
build_flags = 
  -I .
  -I grbl
  -I Inc
  -I GD32F30x_usbd_library/class/device/cdc/Include
  -I GD32F30x_usbd_library/device/Include
  -I GD32F30x_usbd_library/usbd/Include
#   Default RX_BUFFER_SIZE = 1024
  -D RX_BUFFER_SIZE=2048
#   Default NVS_size is 2048
#  -D NVS_SIZE=1536
#  Define STM32 platform for core module compability
  -D STM32F303xC
lib_deps =
  grbl
lib_extra_dirs =
  .
#  -D OVERRIDE_MY_MACHINE

[env]
platform = https://github.com/CommunityGD32Cores/platform-gd32.git
framework = spl
# Do not produce .a files for lib deps (which would prevent them from overriding weak symbols)
lib_archive = no
lib_ldf_mode = off

# Generic map is used. BluepillPlus GD32
[env:gd32f303cc]
board = genericGD32F303CC
build_flags = ${common.build_flags}
lib_deps = ${common.lib_deps}
lib_extra_dirs = ${common.lib_extra_dirs}
upload_protocol = stlink

# Generic map is used. BluepillPlus GD32
# Using modified GD32 usbd cdc library
[env:gd32f303cc_usb]
board = genericGD32F303CC
build_flags = ${common.build_flags}
  -D USB_SERIAL_CDC=1
  -D BLUEPILL_LED
lib_deps = ${common.lib_deps}
  usbd
  device
  class
lib_extra_dirs = ${common.lib_extra_dirs}
  GD32F30x_usbd_library
upload_flags = -c set CPUTAPID 0x2ba01477
upload_protocol = stlink

# Attention! Incomplete pin map for this board!
[env:lunyee_3axis]
board = genericGD32F303CC
build_flags = ${common.build_flags}
  -D BOARD_LUNYEE3AXIS
lib_deps = ${common.lib_deps}
lib_extra_dirs = ${common.lib_extra_dirs}
upload_protocol = stlink
